[package]
name = "signed_integers"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[dependencies]
cw20 = { version = "1.1.0" }
cosmwasm-storage = { version = "1.5.2"}
cosmwasm-std = { version = "1.5.3", features = ["iterator"] }
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
cw-storage-plus = "0.16.0"
thiserror = "1.0.58"
nibiru-std = "0.0.3"
schemars = "0.8.20"
cosmwasm-schema = "2.0.3"
cw-ownable = "0.5.1"
serde_json = "1.0.117"
